jpanda:
  swagger:
    config:
      base-package: cn.jpanda.demo.manager.controller
      title: JPanda Spring Boot Security 快速开发
      description: JPanda Spring Boot Security 快速开发平台API接口文档
      version: 1.0
      enable: true
      auth: false
  exception:
    handler:
      return-error-info: false
  auto-result:
    include-packages: cn\.jpanda\.demo\.manager\.controller\.api.*
server:
  port: 8080
  servlet:
    context-path: /jpanda
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: ./logs
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tommy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: COURSE-MANAGER-HIKARICP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  application:
    name: jpanda-demo-manager
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:logback.xml
  level:
    root: debug
    cn:
      jpanda:
        course:
          manager: DEBUG
    org:
      springframework:
        security: DEBUG
mybatis-plus:
  global-config:
    db-column-underline: true
    logic-delete-value: 2
    logic-not-delete-value: 1
    refresh-mapper: true
  mapper-locations: classpath:cn/jpanda/demo/manager/dao/**/*.xml
  type-enums-package: cn.jpanda.demo.manager.enums.ecode
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl